var k=!0,p=null,s=!1;window.PR_SHOULD_USE_CONTINUATION=k;function y(b,e,d,j){e&&(b={a:e,c:b},d(b),j.push.apply(j,b.d))}
function D(b,e){function d(b){for(var a=b.c,g=[a,"pln"],j=0,f=b.a.match(z)||[],o={},h=0,x=f.length;h<x;++h){var c=f[h],i=o[c],l=void 0,n;if("string"===typeof i)n=s;else{var A=m[c.charAt(0)];if(A)l=c.match(A[1]),i=A[0];else{for(n=0;n<B;++n)if(A=e[n],l=c.match(A[1])){i=A[0];break}l||(i="pln")}if((n=5<=i.length&&"lang-"===i.substring(0,5))&&!(l&&"string"===typeof l[1]))n=s,i="src";n||(o[c]=i)}A=j;j+=c.length;if(n){n=l[1];var J=c.indexOf(n),r=J+n.length;l[2]&&(r=c.length-l[2].length,J=r-n.length);i=i.substring(5);
y(a+A,c.substring(0,J),d,g);y(a+A+J,n,F(i,n),g);y(a+A+r,c.substring(r),d,g)}else g.push(a+A,i)}b.d=g}function j(b){for(var a=b.source.match(RegExp("(?:\\[(?:[^\\x5C\\x5D]|\\\\[\\s\\S])*\\]|\\\\u[A-Fa-f0-9]{4}|\\\\x[A-Fa-f0-9]{2}|\\\\[0-9]+|\\\\[^ux0-9]|\\(\\?[:!=]|[\\(\\)\\^]|[^\\x5B\\x5C\\(\\)\\^]+)","g")),e=a.length,d=[],f=0,c=0;f<e;++f){var h=a[f];"("===h?++c:"\\"===h.charAt(0)&&(h=+h.substring(1))&&h<=c&&(d[h]=-1)}for(f=1;f<d.length;++f)-1===d[f]&&(d[f]=++o);for(c=f=0;f<e;++f)h=a[f],"("===h?(++c,
void 0===d[c]&&(a[f]="(?:")):"\\"===h.charAt(0)&&(h=+h.substring(1))&&h<=c&&(a[f]="\\"+d[c]);for(c=f=0;f<e;++f)"^"===a[f]&&"^"!==a[f+1]&&(a[f]="");if(b.ignoreCase&&g)for(f=0;f<e;++f)h=a[f],b=h.charAt(0),2<=h.length&&"["===b?a[f]=v(h):"\\"!==b&&(a[f]=h.replace(/[a-zA-Z]/g,function(a){a=a.charCodeAt(0);return"["+String.fromCharCode(a&-33,a|32)+"]"}));return a.join("")}function v(a){for(var b=a.substring(1,a.length-1).match(/\\u[0-9A-Fa-f]{4}|\\x[0-9A-Fa-f]{2}|\\[0-3][0-7]{0,2}|\\[0-7]{1,2}|\\[\s\S]|-|[^-\\]/g),
a=[],c=[],d="^"===b[0],f=d?1:0,e=b.length;f<e;++f){var h=b[f];if(/\\[bdsw]/i.test(h))a.push(h);else{var h=q(h),g;f+2<e&&"-"===b[f+1]?(g=q(b[f+2]),f+=2):g=h;c.push([h,g]);65>g||122<h||(65>g||90<h||c.push([Math.max(65,h)|32,Math.min(g,90)|32]),97>g||122<h||c.push([Math.max(97,h)&-33,Math.min(g,122)&-33]))}}c.sort(function(a,b){return a[0]-b[0]||b[1]-a[1]});b=[];h=[NaN,NaN];for(f=0;f<c.length;++f)e=c[f],e[0]<=h[1]+1?h[1]=Math.max(h[1],e[1]):b.push(h=e);c=["["];d&&c.push("^");c.push.apply(c,a);for(f=
0;f<b.length;++f)e=b[f],c.push(w(e[0])),e[1]>e[0]&&(e[1]+1>e[0]&&c.push("-"),c.push(w(e[1])));c.push("]");return c.join("")}function w(a){if(32>a)return(16>a?"\\x0":"\\x")+a.toString(16);a=String.fromCharCode(a);if("\\"===a||"-"===a||"["===a||"]"===a)a="\\"+a;return a}function q(a){var b=a.charCodeAt(0);if(92!==b)return b;var c=a.charAt(1);return(b=E[c])?b:"0"<=c&&"7">=c?parseInt(a.substring(1),8):"u"===c||"x"===c?parseInt(a.substring(2),16):a.charCodeAt(1)}for(var m={},z,i=b.concat(e),c=[],l={},
u=0,r=i.length;u<r;++u){var a=i[u],x=a[3];if(x)for(var n=x.length;0<=--n;)m[x.charAt(n)]=a;a=a[1];x=""+a;l.hasOwnProperty(x)||(c.push(a),l[x]=p)}c.push(/[\0-\uffff]/);for(var o=0,g=s,i=s,l=0,u=c.length;l<u;++l)if(r=c[l],r.ignoreCase)i=k;else if(/[a-z]/i.test(r.source.replace(/\\u[0-9a-f]{4}|\\x[0-9a-f]{2}|\\[^ux]/gi,""))){g=k;i=s;break}for(var E={b:8,t:9,n:10,v:11,f:12,r:13},a=[],l=0,u=c.length;l<u;++l){r=c[l];if(r.global||r.multiline)throw Error(""+r);a.push("(?:"+j(r)+")")}z=RegExp(a.join("|"),
i?"gi":"g");var B=e.length;return d}
function K(b){var e=[],d=[];b.tripleQuotedStrings?e.push(["str",/^(?:\'\'\'(?:[^\'\\]|\\[\s\S]|\'{1,2}(?=[^\']))*(?:\'\'\'|$)|\"\"\"(?:[^\"\\]|\\[\s\S]|\"{1,2}(?=[^\"]))*(?:\"\"\"|$)|\'(?:[^\\\']|\\[\s\S])*(?:\'|$)|\"(?:[^\\\"]|\\[\s\S])*(?:\"|$))/,p,"'\""]):b.multiLineStrings?e.push(["str",/^(?:\'(?:[^\\\']|\\[\s\S])*(?:\'|$)|\"(?:[^\\\"]|\\[\s\S])*(?:\"|$)|\`(?:[^\\\`]|\\[\s\S])*(?:\`|$))/,p,"'\"`"]):e.push(["str",/^(?:\'(?:[^\\\'\r\n]|\\.)*(?:\'|$)|\"(?:[^\\\"\r\n]|\\.)*(?:\"|$))/,p,"\"'"]);b.verbatimStrings&&
d.push(["str",/^@\"(?:[^\"]|\"\")*(?:\"|$)/,p]);var j=b.hashComments;j&&(b.cStyleComments?(1<j?e.push(["com",/^#(?:##(?:[^#]|#(?!##))*(?:###|$)|.*)/,p,"#"]):e.push(["com",/^#(?:(?:define|elif|else|endif|error|ifdef|include|ifndef|line|pragma|undef|warning)\b|[^\r\n]*)/,p,"#"]),d.push(["str",/^<(?:(?:(?:\.\.\/)*|\/?)(?:[\w-]+(?:\/[\w-]+)+)?[\w-]+\.h|[a-z]\w*)>/,p])):e.push(["com",/^#[^\r\n]*/,p,"#"]));b.cStyleComments&&(d.push(["com",/^\/\/[^\r\n]*/,p]),d.push(["com",/^\/\*[\s\S]*?(?:\*\/|$)/,p]));
b.regexLiterals&&d.push(["lang-regex",RegExp("^(?:^^\\.?|[+-]|\\!|\\!=|\\!==|\\#|\\%|\\%=|&|&&|&&=|&=|\\(|\\*|\\*=|\\+=|\\,|\\-=|\\->|\\/|\\/=|:|::|\\;|<|<<|<<=|<=|=|==|===|>|>=|>>|>>=|>>>|>>>=|\\?|\\@|\\[|\\^|\\^=|\\^\\^|\\^\\^=|\\{|\\||\\|=|\\|\\||\\|\\|=|\\~|break|case|continue|delete|do|else|finally|instanceof|return|throw|try|typeof)\\s*(/(?=[^/*])(?:[^/\\x5B\\x5C]|\\x5C[\\s\\S]|\\x5B(?:[^\\x5C\\x5D]|\\x5C[\\s\\S])*(?:\\x5D|$))+/)")]);(j=b.types)&&d.push(["typ",j]);b=(""+b.keywords).replace(/^ | $/g,
"");b.length&&d.push(["kwd",RegExp("^(?:"+b.replace(/[\s,]+/g,"|")+")\\b"),p]);e.push(["pln",/^\s+/,p," \r\n\t\xa0"]);d.push(["lit",/^@[a-z_$][a-z_$@0-9]*/i,p],["typ",/^(?:[@_]?[A-Z]+[a-z][A-Za-z_$@0-9]*|\w+_t\b)/,p],["pln",/^[a-z_$][a-z_$@0-9]*/i,p],["lit",/^(?:0x[a-f0-9]+|(?:\d(?:_\d+)*\d*(?:\.\d*)?|\.\d\+)(?:e[+\-]?\d+)?)[a-z]*/i,p,"0123456789"],["pln",/^\\[\s\S]?/,p],["pun",/^.[^\s\w\.$@\'\"\`\/\#\\]*/,p]);return D(e,d)}
function L(b,e){function d(a){switch(a.nodeType){case 1:if(v.test(a.className))break;if("BR"===a.nodeName)j(a),a.parentNode&&a.parentNode.removeChild(a);else for(a=a.firstChild;a;a=a.nextSibling)d(a);break;case 3:case 4:if(z){var b=a.nodeValue,c=b.match(w);if(c){var e=b.substring(0,c.index);a.nodeValue=e;(b=b.substring(c.index+c[0].length))&&a.parentNode.insertBefore(q.createTextNode(b),a.nextSibling);j(a);e||a.parentNode.removeChild(a)}}}}function j(a){function b(a,c){var e=c?a.cloneNode(s):a,d=
a.parentNode;if(d){var d=b(d,1),j=a.nextSibling;d.appendChild(e);for(var i=j;i;i=j)j=i.nextSibling,d.appendChild(i)}return e}for(;!a.nextSibling;)if(a=a.parentNode,!a)return;for(var a=b(a.nextSibling,0),c;(c=a.parentNode)&&1===c.nodeType;)a=c;i.push(a)}var v=/(?:^|\s)nocode(?:\s|$)/,w=/\r\n?|\n/,q=b.ownerDocument,m;b.currentStyle?m=b.currentStyle.whiteSpace:window.getComputedStyle&&(m=q.defaultView.getComputedStyle(b,p).getPropertyValue("white-space"));var z=m&&"pre"===m.substring(0,3);for(m=q.createElement("LI");b.firstChild;)m.appendChild(b.firstChild);
for(var i=[m],c=0;c<i.length;++c)d(i[c]);e===(e|0)&&i[0].setAttribute("value",e);var l=q.createElement("OL");l.className="linenums";for(var u=Math.max(0,e-1|0)||0,c=0,r=i.length;c<r;++c)m=i[c],m.className="L"+(c+u)%10,m.firstChild||m.appendChild(q.createTextNode("\xa0")),l.appendChild(m);b.appendChild(l)}function M(b,e){for(var d=e.length;0<=--d;){var j=e[d];N.hasOwnProperty(j)?window.console&&console.warn("cannot override language handler %s",j):N[j]=b}}
function F(b,e){if(!b||!N.hasOwnProperty(b))b=/^\s*</.test(e)?"default-markup":"default-code";return N[b]}
function S(b){var e,d,j=b.e;try{var v=b.g,w=function(a){switch(a.nodeType){case 1:if(q.test(a.className))break;for(var b=a.firstChild;b;b=b.nextSibling)w(b);b=a.nodeName;if("BR"===b||"LI"===b)m[c]="\n",i[c<<1]=z++,i[c++<<1|1]=a;break;case 3:case 4:b=a.nodeValue,b.length&&(b=u?b.replace(/\r\n?/g,"\n"):b.replace(/[ \t\r\n]+/g," "),m[c]=b,i[c<<1]=z,z+=b.length,i[c++<<1|1]=a)}},q=/(?:^|\s)nocode(?:\s|$)/,m=[],z=0,i=[],c=0,l;v.currentStyle?l=v.currentStyle.whiteSpace:window.getComputedStyle&&(l=document.defaultView.getComputedStyle(v,
p).getPropertyValue("white-space"));var u=l&&"pre"===l.substring(0,3);w(v);e=m.join("").replace(/\n$/,"");d=i;b.a=e;b.i=d;b.c=0;F(j,e)(b);var r=/\bMSIE\b/.test(navigator.userAgent);e=/\n/g;var a=b.a,x=a.length;d=0;var n=b.i,o=n.length,j=0,g=b.d,E=g.length,b=0;g[E]=x;var B,t;for(t=B=0;t<E;)g[t]!==g[t+2]?(g[B++]=g[t++],g[B++]=g[t++]):t+=2;E=B;for(t=B=0;t<E;){for(var ca=g[t],O=g[t+1],C=t+2;C+2<=E&&g[C+1]===O;)C+=2;g[B++]=ca;g[B++]=O;t=C}for(g.length=B;j<o;){var f=n[j+2]||x,P=g[b+2]||x,C=Math.min(f,P),
h=n[j+1],G;if(1!==h.nodeType&&(G=a.substring(d,C))){r&&(G=G.replace(e,"\r"));h.nodeValue=G;var Q=h.ownerDocument,H=Q.createElement("SPAN");H.className=g[b+1];var R=h.parentNode;R.replaceChild(H,h);H.appendChild(h);d<f&&(n[j+1]=h=Q.createTextNode(a.substring(C,f)),R.insertBefore(h,H.nextSibling))}d=C;d>=f&&(j+=2);d>=P&&(b+=2)}}catch(I){"console"in window&&console.log(I&&I.stack?I.stack:I)}}
var T=["break,continue,do,else,for,if,return,while"],U=[[T,"auto,case,char,const,default,double,enum,extern,float,goto,int,long,register,short,signed,sizeof,static,struct,switch,typedef,union,unsigned,void,volatile"],"catch,class,delete,false,import,new,operator,private,protected,public,this,throw,true,try,typeof"],V=[U,"alignof,align_union,asm,axiom,bool,concept,concept_map,const_cast,constexpr,decltype,dynamic_cast,explicit,export,friend,inline,late_check,mutable,namespace,nullptr,reinterpret_cast,static_assert,static_cast,template,typeid,typename,using,virtual,where"],
W=[U,"abstract,boolean,byte,extends,final,finally,implements,import,instanceof,null,native,package,strictfp,super,synchronized,throws,transient"],X=[W,"as,base,by,checked,decimal,delegate,descending,dynamic,event,fixed,foreach,from,group,implicit,in,interface,internal,into,is,lock,object,out,override,orderby,params,partial,readonly,ref,sbyte,sealed,stackalloc,string,select,uint,ulong,unchecked,unsafe,ushort,var"],Y=[U,"debugger,eval,export,function,get,null,set,undefined,var,with,Infinity,NaN"],Z=
[T,"and,as,assert,class,def,del,elif,except,exec,finally,from,global,import,in,is,lambda,nonlocal,not,or,pass,print,raise,try,with,yield,False,True,None"],$=[T,"alias,and,begin,case,class,def,defined,elsif,end,ensure,false,in,module,next,nil,not,or,redo,rescue,retry,self,super,then,true,undef,unless,until,when,yield,BEGIN,END"],aa=[T,"case,done,elif,esac,eval,fi,function,in,local,set,then,until"],ba=/^(DIR|FILE|vector|(de|priority_)?queue|list|stack|(const_)?iterator|(multi)?(set|map)|bitset|u?(int|float)\d*)/,
da=/\S/,ea=K({keywords:[V,X,Y,"caller,delete,die,do,dump,elsif,eval,exit,foreach,for,goto,if,import,last,local,my,next,no,our,print,package,redo,require,sub,undef,unless,until,use,wantarray,while,BEGIN,END"+Z,$,aa],hashComments:k,cStyleComments:k,multiLineStrings:k,regexLiterals:k}),N={};M(ea,["default-code"]);
M(D([],[["pln",/^[^<?]+/],["dec",/^<!\w[^>]*(?:>|$)/],["com",/^<\!--[\s\S]*?(?:-\->|$)/],["lang-",/^<\?([\s\S]+?)(?:\?>|$)/],["lang-",/^<%([\s\S]+?)(?:%>|$)/],["pun",/^(?:<[%?]|[%?]>)/],["lang-",/^<xmp\b[^>]*>([\s\S]+?)<\/xmp\b[^>]*>/i],["lang-js",/^<script\b[^>]*>([\s\S]*?)(<\/script\b[^>]*>)/i],["lang-css",/^<style\b[^>]*>([\s\S]*?)(<\/style\b[^>]*>)/i],["lang-in.tag",/^(<\/?[a-z][^<>]*>)/i]]),"default-markup htm html mxml xhtml xml xsl".split(" "));
M(D([["pln",/^[\s]+/,p," \t\r\n"],["atv",/^(?:\"[^\"]*\"?|\'[^\']*\'?)/,p,"\"'"]],[["tag",/^^<\/?[a-z](?:[\w.:-]*\w)?|\/?>$/i],["atn",/^(?!style[\s=]|on)[a-z](?:[\w:-]*\w)?/i],["lang-uq.val",/^=\s*([^>\'\"\s]*(?:[^>\'\"\s\/]|\/(?=\s)))/],["pun",/^[=<>\/]+/],["lang-js",/^on\w+\s*=\s*\"([^\"]+)\"/i],["lang-js",/^on\w+\s*=\s*\'([^\']+)\'/i],["lang-js",/^on\w+\s*=\s*([^\"\'>\s]+)/i],["lang-css",/^style\s*=\s*\"([^\"]+)\"/i],["lang-css",/^style\s*=\s*\'([^\']+)\'/i],["lang-css",/^style\s*=\s*([^\"\'>\s]+)/i]]),
["in.tag"]);M(D([],[["atv",/^[\s\S]+/]]),["uq.val"]);M(K({keywords:V,hashComments:k,cStyleComments:k,types:ba}),"c cc cpp cxx cyc m".split(" "));M(K({keywords:"null,true,false"}),["json"]);M(K({keywords:X,hashComments:k,cStyleComments:k,verbatimStrings:k,types:ba}),["cs"]);M(K({keywords:W,cStyleComments:k}),["java"]);M(K({keywords:aa,hashComments:k,multiLineStrings:k}),["bsh","csh","sh"]);M(K({keywords:Z,hashComments:k,multiLineStrings:k,tripleQuotedStrings:k}),["cv","py"]);
M(K({keywords:"caller,delete,die,do,dump,elsif,eval,exit,foreach,for,goto,if,import,last,local,my,next,no,our,print,package,redo,require,sub,undef,unless,until,use,wantarray,while,BEGIN,END",hashComments:k,multiLineStrings:k,regexLiterals:k}),["perl","pl","pm"]);M(K({keywords:$,hashComments:k,multiLineStrings:k,regexLiterals:k}),["rb"]);M(K({keywords:Y,cStyleComments:k,regexLiterals:k}),["js"]);
M(K({keywords:"all,and,by,catch,class,else,extends,false,finally,for,if,in,is,isnt,loop,new,no,not,null,of,off,on,or,return,super,then,true,try,unless,until,when,while,yes",hashComments:3,cStyleComments:k,multilineStrings:k,tripleQuotedStrings:k,regexLiterals:k}),["coffee"]);M(D([],[["str",/^[\s\S]+/]]),["regex"]);window.prettyPrintOne=function(b,e,d){var j=document.createElement("PRE");j.innerHTML=b;d&&L(j,d);S({e:e,h:d,g:j});return j.innerHTML};
window.prettyPrint=function(b,e){function d(b,a){return a?document.getElementById(a).getElementsByTagName(b):document.getElementsByTagName(b)}function j(){for(var b=window.PR_SHOULD_USE_CONTINUATION?i.now()+250:Infinity;c<w.length&&i.now()<b;c++){var a=w[c],d=a.className;if(0<=d.indexOf("prettyprint")){var d=d.match(u),n,o;if(o=!d){o=a;for(var g=void 0,m=o.firstChild;m;m=m.nextSibling)var q=m.nodeType,g=1===q?g?o:m:3===q?da.test(m.nodeValue)?o:g:g;o=(n=g===o?void 0:g)&&"CODE"===n.tagName}o&&(d=n.className.match(u));
d&&(d=d[1]);o=s;for(g=a.parentNode;g;g=g.parentNode)if(("pre"===g.tagName||"code"===g.tagName||"xmp"===g.tagName)&&g.className&&0<=g.className.indexOf("prettyprint")){o=k;break}o||((o=(o=a.className.match(/\blinenums\b(?::(\d+))?/))?o[1]&&o[1].length?+o[1]:k:s)&&L(a,o),l={e:d,g:a,h:o},S(l))}}c<w.length?setTimeout(j,250):e&&e()}!e&&(b&&"function"===typeof b)&&(e=b,b=void 0);for(var v=[d("pre",b),d("code",b),d("xmp",b)],w=[],q=0;q<v.length;++q)for(var m=0,z=v[q].length;m<z;++m)w.push(v[q][m]);var v=
p,i=Date;i.now||(i={now:function(){return+new Date}});var c=0,l,u=/\blang(?:uage)?-([\w.]+)(?!\S)/;j()};window.PR={createSimpleLexer:D,registerLangHandler:M,sourceDecorator:K,PR_ATTRIB_NAME:"atn",PR_ATTRIB_VALUE:"atv",PR_COMMENT:"com",PR_DECLARATION:"dec",PR_KEYWORD:"kwd",PR_LITERAL:"lit",PR_NOCODE:"nocode",PR_PLAIN:"pln",PR_PUNCTUATION:"pun",PR_SOURCE:"src",PR_STRING:"str",PR_TAG:"tag",PR_TYPE:"typ"};
