var l=!0,p=null,s=!1;window.PR_SHOULD_USE_CONTINUATION=l;function y(b,i,c,f){i&&(b={a:i,c:b},c(b),f.push.apply(f,b.d))}
function D(b,i){function c(b){for(var a=b.c,d=[a,"pln"],f=0,g=b.a.match(v)||[],o={},h=0,n=g.length;h<n;++h){var k=g[h],j=o[k],m=void 0,e;if("string"===typeof j)e=s;else{var z=q[k.charAt(0)];if(z)m=k.match(z[1]),j=z[0];else{for(e=0;e<B;++e)if(z=i[e],m=k.match(z[1])){j=z[0];break}m||(j="pln")}if((e=5<=j.length&&"lang-"===j.substring(0,5))&&!(m&&"string"===typeof m[1]))e=s,j="src";e||(o[k]=j)}z=f;f+=k.length;if(e){e=m[1];var J=k.indexOf(e),t=J+e.length;m[2]&&(t=k.length-m[2].length,J=t-e.length);j=j.substring(5);
y(a+z,k.substring(0,J),c,d);y(a+z+J,e,F(j,e),d);y(a+z+t,k.substring(t),c,d)}else d.push(a+z,j)}b.d=d}function f(b){for(var a=b.source.match(RegExp("(?:\\[(?:[^\\x5C\\x5D]|\\\\[\\s\\S])*\\]|\\\\u[A-Fa-f0-9]{4}|\\\\x[A-Fa-f0-9]{2}|\\\\[0-9]+|\\\\[^ux0-9]|\\(\\?[:!=]|[\\(\\)\\^]|[^\\x5B\\x5C\\(\\)\\^]+)","g")),d=a.length,c=[],g=0,f=0;g<d;++g){var h=a[g];"("===h?++f:"\\"===h.charAt(0)&&(h=+h.substring(1))&&h<=f&&(c[h]=-1)}for(g=1;g<c.length;++g)-1===c[g]&&(c[g]=++t);for(f=g=0;g<d;++g)h=a[g],"("===h?(++f,
void 0===c[f]&&(a[g]="(?:")):"\\"===h.charAt(0)&&(h=+h.substring(1))&&h<=f&&(a[g]="\\"+c[f]);for(f=g=0;g<d;++g)"^"===a[g]&&"^"!==a[g+1]&&(a[g]="");if(b.ignoreCase&&k)for(g=0;g<d;++g)h=a[g],b=h.charAt(0),2<=h.length&&"["===b?a[g]=w(h):"\\"!==b&&(a[g]=h.replace(/[a-zA-Z]/g,function(a){a=a.charCodeAt(0);return"["+String.fromCharCode(a&-33,a|32)+"]"}));return a.join("")}function w(a){for(var b=a.substring(1,a.length-1).match(/\\u[0-9A-Fa-f]{4}|\\x[0-9A-Fa-f]{2}|\\[0-3][0-7]{0,2}|\\[0-7]{1,2}|\\[\s\S]|-|[^-\\]/g),
a=[],d=[],f="^"===b[0],g=f?1:0,c=b.length;g<c;++g){var h=b[g];if(/\\[bdsw]/i.test(h))a.push(h);else{var h=x(h),e;g+2<c&&"-"===b[g+1]?(e=x(b[g+2]),g+=2):e=h;d.push([h,e]);65>e||122<h||(65>e||90<h||d.push([Math.max(65,h)|32,Math.min(e,90)|32]),97>e||122<h||d.push([Math.max(97,h)&-33,Math.min(e,122)&-33]))}}d.sort(function(a,b){return a[0]-b[0]||b[1]-a[1]});b=[];h=[NaN,NaN];for(g=0;g<d.length;++g)c=d[g],c[0]<=h[1]+1?h[1]=Math.max(h[1],c[1]):b.push(h=c);d=["["];f&&d.push("^");d.push.apply(d,a);for(g=
0;g<b.length;++g)c=b[g],d.push(A(c[0])),c[1]>c[0]&&(c[1]+1>c[0]&&d.push("-"),d.push(A(c[1])));d.push("]");return d.join("")}function A(a){if(32>a)return(16>a?"\\x0":"\\x")+a.toString(16);a=String.fromCharCode(a);if("\\"===a||"-"===a||"["===a||"]"===a)a="\\"+a;return a}function x(a){var b=a.charCodeAt(0);if(92!==b)return b;var d=a.charAt(1);return(b=E[d])?b:"0"<=d&&"7">=d?parseInt(a.substring(1),8):"u"===d||"x"===d?parseInt(a.substring(2),16):a.charCodeAt(1)}for(var q={},v,m=b.concat(i),n=[],e={},
r=0,j=m.length;r<j;++r){var a=m[r],d=a[3];if(d)for(var o=d.length;0<=--o;)q[d.charAt(o)]=a;a=a[1];d=""+a;e.hasOwnProperty(d)||(n.push(a),e[d]=p)}n.push(/[\0-\uffff]/);for(var t=0,k=s,m=s,e=0,r=n.length;e<r;++e)if(j=n[e],j.ignoreCase)m=l;else if(/[a-z]/i.test(j.source.replace(/\\u[0-9a-f]{4}|\\x[0-9a-f]{2}|\\[^ux]/gi,""))){k=l;m=s;break}for(var E={b:8,t:9,n:10,v:11,f:12,r:13},a=[],e=0,r=n.length;e<r;++e){j=n[e];if(j.global||j.multiline)throw Error(""+j);a.push("(?:"+f(j)+")")}v=RegExp(a.join("|"),
m?"gi":"g");var B=i.length;return c}
function K(b){var i=[],c=[];b.tripleQuotedStrings?i.push(["str",/^(?:\'\'\'(?:[^\'\\]|\\[\s\S]|\'{1,2}(?=[^\']))*(?:\'\'\'|$)|\"\"\"(?:[^\"\\]|\\[\s\S]|\"{1,2}(?=[^\"]))*(?:\"\"\"|$)|\'(?:[^\\\']|\\[\s\S])*(?:\'|$)|\"(?:[^\\\"]|\\[\s\S])*(?:\"|$))/,p,"'\""]):b.multiLineStrings?i.push(["str",/^(?:\'(?:[^\\\']|\\[\s\S])*(?:\'|$)|\"(?:[^\\\"]|\\[\s\S])*(?:\"|$)|\`(?:[^\\\`]|\\[\s\S])*(?:\`|$))/,p,"'\"`"]):i.push(["str",/^(?:\'(?:[^\\\'\r\n]|\\.)*(?:\'|$)|\"(?:[^\\\"\r\n]|\\.)*(?:\"|$))/,p,"\"'"]);b.verbatimStrings&&
c.push(["str",/^@\"(?:[^\"]|\"\")*(?:\"|$)/,p]);var f=b.hashComments;f&&(b.cStyleComments?(1<f?i.push(["com",/^#(?:##(?:[^#]|#(?!##))*(?:###|$)|.*)/,p,"#"]):i.push(["com",/^#(?:(?:define|elif|else|endif|error|ifdef|include|ifndef|line|pragma|undef|warning)\b|[^\r\n]*)/,p,"#"]),c.push(["str",/^<(?:(?:(?:\.\.\/)*|\/?)(?:[\w-]+(?:\/[\w-]+)+)?[\w-]+\.h|[a-z]\w*)>/,p])):i.push(["com",/^#[^\r\n]*/,p,"#"]));b.cStyleComments&&(c.push(["com",/^\/\/[^\r\n]*/,p]),c.push(["com",/^\/\*[\s\S]*?(?:\*\/|$)/,p]));
b.regexLiterals&&c.push(["lang-regex",RegExp("^(?:^^\\.?|[+-]|\\!|\\!=|\\!==|\\#|\\%|\\%=|&|&&|&&=|&=|\\(|\\*|\\*=|\\+=|\\,|\\-=|\\->|\\/|\\/=|:|::|\\;|<|<<|<<=|<=|=|==|===|>|>=|>>|>>=|>>>|>>>=|\\?|\\@|\\[|\\^|\\^=|\\^\\^|\\^\\^=|\\{|\\||\\|=|\\|\\||\\|\\|=|\\~|break|case|continue|delete|do|else|finally|instanceof|return|throw|try|typeof)\\s*(/(?=[^/*])(?:[^/\\x5B\\x5C]|\\x5C[\\s\\S]|\\x5B(?:[^\\x5C\\x5D]|\\x5C[\\s\\S])*(?:\\x5D|$))+/)")]);(f=b.types)&&c.push(["typ",f]);b=(""+b.keywords).replace(/^ | $/g,
"");b.length&&c.push(["kwd",RegExp("^(?:"+b.replace(/[\s,]+/g,"|")+")\\b"),p]);i.push(["pln",/^\s+/,p," \r\n\t\xa0"]);c.push(["lit",/^@[a-z_$][a-z_$@0-9]*/i,p],["typ",/^(?:[@_]?[A-Z]+[a-z][A-Za-z_$@0-9]*|\w+_t\b)/,p],["pln",/^[a-z_$][a-z_$@0-9]*/i,p],["lit",/^(?:0x[a-f0-9]+|(?:\d(?:_\d+)*\d*(?:\.\d*)?|\.\d\+)(?:e[+\-]?\d+)?)[a-z]*/i,p,"0123456789"],["pln",/^\\[\s\S]?/,p],["pun",/^.[^\s\w\.$@\'\"\`\/\#\\]*/,p]);return D(i,c)}
function L(b,i){function c(a){switch(a.nodeType){case 1:if(w.test(a.className))break;if("BR"===a.nodeName)f(a),a.parentNode&&a.parentNode.removeChild(a);else for(a=a.firstChild;a;a=a.nextSibling)c(a);break;case 3:case 4:if(v){var b=a.nodeValue,e=b.match(A);if(e){var i=b.substring(0,e.index);a.nodeValue=i;(b=b.substring(e.index+e[0].length))&&a.parentNode.insertBefore(x.createTextNode(b),a.nextSibling);f(a);i||a.parentNode.removeChild(a)}}}}function f(a){function b(a,c){var f=c?a.cloneNode(s):a,e=
a.parentNode;if(e){var e=b(e,1),i=a.nextSibling;e.appendChild(f);for(var j=i;j;j=i)i=j.nextSibling,e.appendChild(j)}return f}for(;!a.nextSibling;)if(a=a.parentNode,!a)return;for(var a=b(a.nextSibling,0),c;(c=a.parentNode)&&1===c.nodeType;)a=c;m.push(a)}var w=/(?:^|\s)nocode(?:\s|$)/,A=/\r\n?|\n/,x=b.ownerDocument,q;b.currentStyle?q=b.currentStyle.whiteSpace:window.getComputedStyle&&(q=x.defaultView.getComputedStyle(b,p).getPropertyValue("white-space"));var v=q&&"pre"===q.substring(0,3);for(q=x.createElement("LI");b.firstChild;)q.appendChild(b.firstChild);
for(var m=[q],n=0;n<m.length;++n)c(m[n]);i===(i|0)&&m[0].setAttribute("value",i);var e=x.createElement("OL");e.className="linenums";for(var r=Math.max(0,i-1|0)||0,n=0,j=m.length;n<j;++n)q=m[n],q.className="L"+(n+r)%10,q.firstChild||q.appendChild(x.createTextNode("\xa0")),e.appendChild(q);b.appendChild(e)}function M(b,i){for(var c=i.length;0<=--c;){var f=i[c];N.hasOwnProperty(f)?window.console&&console.warn("cannot override language handler %s",f):N[f]=b}}
function F(b,i){if(!b||!N.hasOwnProperty(b))b=/^\s*</.test(i)?"default-markup":"default-code";return N[b]}
function S(b){var i,c,f=b.e;try{var w=b.g,A=function(a){switch(a.nodeType){case 1:if(x.test(a.className))break;for(var b=a.firstChild;b;b=b.nextSibling)A(b);b=a.nodeName;if("BR"===b||"LI"===b)q[n]="\n",m[n<<1]=v++,m[n++<<1|1]=a;break;case 3:case 4:b=a.nodeValue,b.length&&(b=r?b.replace(/\r\n?/g,"\n"):b.replace(/[ \t\r\n]+/g," "),q[n]=b,m[n<<1]=v,v+=b.length,m[n++<<1|1]=a)}},x=/(?:^|\s)nocode(?:\s|$)/,q=[],v=0,m=[],n=0,e;w.currentStyle?e=w.currentStyle.whiteSpace:window.getComputedStyle&&(e=document.defaultView.getComputedStyle(w,
p).getPropertyValue("white-space"));var r=e&&"pre"===e.substring(0,3);A(w);i=q.join("").replace(/\n$/,"");c=m;b.a=i;b.i=c;b.c=0;F(f,i)(b);var j=/\bMSIE\b/.test(navigator.userAgent);i=/\n/g;var a=b.a,d=a.length;c=0;var o=b.i,t=o.length,f=0,k=b.d,E=k.length,b=0;k[E]=d;var B,u;for(u=B=0;u<E;)k[u]!==k[u+2]?(k[B++]=k[u++],k[B++]=k[u++]):u+=2;E=B;for(u=B=0;u<E;){for(var ca=k[u],O=k[u+1],C=u+2;C+2<=E&&k[C+1]===O;)C+=2;k[B++]=ca;k[B++]=O;u=C}for(k.length=B;f<t;){var g=o[f+2]||d,P=k[b+2]||d,C=Math.min(g,P),
h=o[f+1],G;if(1!==h.nodeType&&(G=a.substring(c,C))){j&&(G=G.replace(i,"\r"));h.nodeValue=G;var Q=h.ownerDocument,H=Q.createElement("SPAN");H.className=k[b+1];var R=h.parentNode;R.replaceChild(H,h);H.appendChild(h);c<g&&(o[f+1]=h=Q.createTextNode(a.substring(C,g)),R.insertBefore(h,H.nextSibling))}c=C;c>=g&&(f+=2);c>=P&&(b+=2)}}catch(I){"console"in window&&console.log(I&&I.stack?I.stack:I)}}
var T=["break,continue,do,else,for,if,return,while"],U=[[T,"auto,case,char,const,default,double,enum,extern,float,goto,int,long,register,short,signed,sizeof,static,struct,switch,typedef,union,unsigned,void,volatile"],"catch,class,delete,false,import,new,operator,private,protected,public,this,throw,true,try,typeof"],V=[U,"alignof,align_union,asm,axiom,bool,concept,concept_map,const_cast,constexpr,decltype,dynamic_cast,explicit,export,friend,inline,late_check,mutable,namespace,nullptr,reinterpret_cast,static_assert,static_cast,template,typeid,typename,using,virtual,where"],
W=[U,"abstract,boolean,byte,extends,final,finally,implements,import,instanceof,null,native,package,strictfp,super,synchronized,throws,transient"],X=[W,"as,base,by,checked,decimal,delegate,descending,dynamic,event,fixed,foreach,from,group,implicit,in,interface,internal,into,is,lock,object,out,override,orderby,params,partial,readonly,ref,sbyte,sealed,stackalloc,string,select,uint,ulong,unchecked,unsafe,ushort,var"],Y=[U,"debugger,eval,export,function,get,null,set,undefined,var,with,Infinity,NaN"],Z=
[T,"and,as,assert,class,def,del,elif,except,exec,finally,from,global,import,in,is,lambda,nonlocal,not,or,pass,print,raise,try,with,yield,False,True,None"],$=[T,"alias,and,begin,case,class,def,defined,elsif,end,ensure,false,in,module,next,nil,not,or,redo,rescue,retry,self,super,then,true,undef,unless,until,when,yield,BEGIN,END"],aa=[T,"case,done,elif,esac,eval,fi,function,in,local,set,then,until"],ba=/^(DIR|FILE|vector|(de|priority_)?queue|list|stack|(const_)?iterator|(multi)?(set|map)|bitset|u?(int|float)\d*)/,
da=/\S/,ea=K({keywords:[V,X,Y,"caller,delete,die,do,dump,elsif,eval,exit,foreach,for,goto,if,import,last,local,my,next,no,our,print,package,redo,require,sub,undef,unless,until,use,wantarray,while,BEGIN,END"+Z,$,aa],hashComments:l,cStyleComments:l,multiLineStrings:l,regexLiterals:l}),N={};M(ea,["default-code"]);
M(D([],[["pln",/^[^<?]+/],["dec",/^<!\w[^>]*(?:>|$)/],["com",/^<\!--[\s\S]*?(?:-\->|$)/],["lang-",/^<\?([\s\S]+?)(?:\?>|$)/],["lang-",/^<%([\s\S]+?)(?:%>|$)/],["pun",/^(?:<[%?]|[%?]>)/],["lang-",/^<xmp\b[^>]*>([\s\S]+?)<\/xmp\b[^>]*>/i],["lang-js",/^<script\b[^>]*>([\s\S]*?)(<\/script\b[^>]*>)/i],["lang-css",/^<style\b[^>]*>([\s\S]*?)(<\/style\b[^>]*>)/i],["lang-in.tag",/^(<\/?[a-z][^<>]*>)/i]]),"default-markup htm html mxml xhtml xml xsl".split(" "));
M(D([["pln",/^[\s]+/,p," \t\r\n"],["atv",/^(?:\"[^\"]*\"?|\'[^\']*\'?)/,p,"\"'"]],[["tag",/^^<\/?[a-z](?:[\w.:-]*\w)?|\/?>$/i],["atn",/^(?!style[\s=]|on)[a-z](?:[\w:-]*\w)?/i],["lang-uq.val",/^=\s*([^>\'\"\s]*(?:[^>\'\"\s\/]|\/(?=\s)))/],["pun",/^[=<>\/]+/],["lang-js",/^on\w+\s*=\s*\"([^\"]+)\"/i],["lang-js",/^on\w+\s*=\s*\'([^\']+)\'/i],["lang-js",/^on\w+\s*=\s*([^\"\'>\s]+)/i],["lang-css",/^style\s*=\s*\"([^\"]+)\"/i],["lang-css",/^style\s*=\s*\'([^\']+)\'/i],["lang-css",/^style\s*=\s*([^\"\'>\s]+)/i]]),
["in.tag"]);M(D([],[["atv",/^[\s\S]+/]]),["uq.val"]);M(K({keywords:V,hashComments:l,cStyleComments:l,types:ba}),"c cc cpp cxx cyc m".split(" "));M(K({keywords:"null,true,false"}),["json"]);M(K({keywords:X,hashComments:l,cStyleComments:l,verbatimStrings:l,types:ba}),["cs"]);M(K({keywords:W,cStyleComments:l}),["java"]);M(K({keywords:aa,hashComments:l,multiLineStrings:l}),["bsh","csh","sh"]);M(K({keywords:Z,hashComments:l,multiLineStrings:l,tripleQuotedStrings:l}),["cv","py"]);
M(K({keywords:"caller,delete,die,do,dump,elsif,eval,exit,foreach,for,goto,if,import,last,local,my,next,no,our,print,package,redo,require,sub,undef,unless,until,use,wantarray,while,BEGIN,END",hashComments:l,multiLineStrings:l,regexLiterals:l}),["perl","pl","pm"]);M(K({keywords:$,hashComments:l,multiLineStrings:l,regexLiterals:l}),["rb"]);M(K({keywords:Y,cStyleComments:l,regexLiterals:l}),["js"]);
M(K({keywords:"all,and,by,catch,class,else,extends,false,finally,for,if,in,is,isnt,loop,new,no,not,null,of,off,on,or,return,super,then,true,try,unless,until,when,while,yes",hashComments:3,cStyleComments:l,multilineStrings:l,tripleQuotedStrings:l,regexLiterals:l}),["coffee"]);M(D([],[["str",/^[\s\S]+/]]),["regex"]);window.prettyPrintOne=function(b,i,c){var f=document.createElement("PRE");f.innerHTML=b;c&&L(f,c);S({e:i,h:c,g:f});return f.innerHTML};
window.prettyPrint=function(b){function i(){for(var c=window.PR_SHOULD_USE_CONTINUATION?q.now()+250:Infinity;v<f.length&&q.now()<c;v++){var r=f[v],j=r.className;if(0<=j.indexOf("prettyprint")){var j=j.match(n),a,d;if(d=!j){d=r;for(var o=void 0,t=d.firstChild;t;t=t.nextSibling)var k=t.nodeType,o=1===k?o?d:t:3===k?da.test(t.nodeValue)?d:o:o;d=(a=o===d?void 0:o)&&"CODE"===a.tagName}d&&(j=a.className.match(n));j&&(j=j[1]);d=s;for(o=r.parentNode;o;o=o.parentNode)if(("pre"===o.tagName||"code"===o.tagName||
"xmp"===o.tagName)&&o.className&&0<=o.className.indexOf("prettyprint")){d=l;break}d||((d=(d=r.className.match(/\blinenums\b(?::(\d+))?/))?d[1]&&d[1].length?+d[1]:l:s)&&L(r,d),m={e:j,g:r,h:d},S(m))}}v<f.length?setTimeout(i,250):b&&b()}for(var c=[document.getElementsByTagName("pre"),document.getElementsByTagName("code"),document.getElementsByTagName("xmp")],f=[],w=0;w<c.length;++w)for(var A=0,x=c[w].length;A<x;++A)f.push(c[w][A]);var c=p,q=Date;q.now||(q={now:function(){return+new Date}});var v=0,m,
n=/\blang(?:uage)?-([\w.]+)(?!\S)/;i()};window.PR={createSimpleLexer:D,registerLangHandler:M,sourceDecorator:K,PR_ATTRIB_NAME:"atn",PR_ATTRIB_VALUE:"atv",PR_COMMENT:"com",PR_DECLARATION:"dec",PR_KEYWORD:"kwd",PR_LITERAL:"lit",PR_NOCODE:"nocode",PR_PLAIN:"pln",PR_PUNCTUATION:"pun",PR_SOURCE:"src",PR_STRING:"str",PR_TAG:"tag",PR_TYPE:"typ"};
